name: irfannadiadi
favicon: null
layout_spectrum: 0.50291
typography_spectrum: 0.362
title: Irfan Nadiadi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040605'
    - '#4f7791'
    - '#b2c3d3'
    - '#dde4ec'
    - '#2f4050'
  brandStrength: 0.75
  lightness: 0.3535461826249957
  saturation: 0.6338243139907718
  rhythmicContrast: 0.8642933175433427
purpose: []
